all:
  children:
    system:
      vars:
        host_interface: ens2
      children:
        client:
          hosts:
            hq-host1:
              host_ip: 172.16.0.100/24
              host_gateway: 172.16.0.1
            site1-host1:
              host_ip: 192.168.1.100/24
              host_gateway: 192.168.1.1
            site2-host1:
              host_ip: 192.168.2.100/24
              host_gateway: 192.168.2.1
        server:
          hosts:
            nso1:
              interfaces:
                ens3:
                  enabled: true
                  ip:
                    primary: 172.16.0.101/24
              static_routes:
                172.16.0.0/24:
                  next_hop: 172.16.0.1
                172.16.254.0/24:
                  next_hop: 172.16.0.1
                172.16.255.0/24:
                  next_hop: 172.16.0.1
                10.0.0.0/8:
                  next_hop: 172.16.0.1
                192.168.0.0/16:
                  next_hop: 172.16.0.1
